local function WriteItemNameDesc(item, name, desc)
    if item == 0 or item == nil then
        return
    end
    for _, c in ipairs(EntityGetComponent(item, "ItemComponent") or {}) do
        ComponentSetValue2(c, "item_name", name)
        ComponentSetValue2(c, "ui_description", desc)
    end
    for _, c in ipairs(EntityGetComponent(item, "UIInfoComponent") or {}) do
        ComponentSetValue2(c, "name", name)
    end
    for _, c in ipairs(EntityGetComponent(item, "AbilityComponent") or {}) do
        ComponentSetValue2(c, "ui_name", name)
    end
end


PICKUPS = {
	{
		id = "beamstone",
		name = "$item_mega_beam_stone",
        desc = "$itemdesc_mega_beam_stone",
		image = "data/ui_gfx/items/beamstone.png",
		path = "data/entities/items/pickup/beamstone.xml",
	},
	{
		id = "evil_eye",
		name = "$item_evil_eye",
        desc = "$item_description_evil_eye",
		image = "data/ui_gfx/items/evil_eye.png",
		path = "data/entities/items/pickup/evil_eye.xml",
	},
	{
		id = "musicstone",
		name = "$item_musicstone",
        desc = "$itemdesc_musicstone",
		image = "data/ui_gfx/items/musicstone.png",
		path = "data/entities/items/pickup/musicstone.xml",
	},
	{
		id = "physics_gold_orb",
		name = "$item_gold_orb",
        desc = "$itemdesc_gold_orb",
		image = "data/ui_gfx/items/orb_gold.png",
		path = "data/entities/items/pickup/physics_gold_orb.xml",
	},
	{
		id = "physics_gold_orb_greed",
		name = "$item_gold_orb_greed",
        desc = "$itemdesc_gold_orb_greed",
		image = "data/ui_gfx/items/orb_gold_greed.png",
		path = "data/entities/items/pickup/physics_gold_orb_greed.xml",
	},
	{
		id = "physics_die",
		name = "$item_die",
        desc = "$itemdesc_die",
		image = "data/ui_gfx/items/die.png",
		path = "data/entities/items/pickup/physics_die.xml",
	},
	{
		id = "physics_greed_die",
		name = "$item_greed_die",
        desc = "$itemdesc_greed_die",
		image = "data/ui_gfx/items/greed_die.png",
		path = "data/entities/items/pickup/physics_greed_die.xml",
	},
	{
		id = "stonestone",
		name = "$item_stonestone",
        desc = "$itemdesc_stonestone",
		image = "data/ui_gfx/items/stonestone.png",
		path = "data/entities/items/pickup/stonestone.xml",
	},
	{
		id = "thunderstone",
		name = "$item_thunderstone",
        desc = "$item_description_thunderstone",
		image = "data/ui_gfx/items/ingredient_1.png",
		path = "data/entities/items/pickup/thunderstone.xml",
	},
	{
		id = "waterstone",
		name = "$item_waterstone",
        desc = "$item_description_waterstone",
		image = "data/ui_gfx/items/waterstone.png",
		path = "data/entities/items/pickup/waterstone.xml",
	},
	{
		id = "brimstone",
		name = "$item_brimstone",
        desc = "$item_description_brimstone",
		image = "data/ui_gfx/items/brimstone.png",
		path = "data/entities/items/pickup/brimstone.xml",
	},
	{
		id = "poopstone",
		name = "$item_kakka",
        desc = "$itemdesc_kakka",
		image = "data/ui_gfx/items/kakke.png",
		path = "data/entities/items/pickup/poopstone.xml",
	},
	{
		id = "newsun",
		name = "$item_seed_e",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/fog_of_war_hole_huge.png",
		path = "data/entities/items/pickup/sun/newsun.xml",
	},
	{
		id = "newsun_dark",
		name = "$item_seed_f",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/sun_big_dark.png",
		path = "data/entities/items/pickup/sun/newsun_dark.xml",
	},
	{
		id = "sunbaby",
		name = "$item_seed_d",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/fog_of_war_hole_huge.png",
		path = "data/entities/items/pickup/sun/sunbaby.xml",
	},
	{
		id = "sunegg",
		name = "$item_seed_b",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/fog_of_war_hole_huge.png",
		path = "data/entities/items/pickup/sun/sunegg.xml",
	},
	{
		id = "sunseed",
		name = "$item_sunseed",
        desc = "$itemdesc_sunseed",
		image = "data/ui_gfx/items/sunseed.png",
		path = "data/entities/items/pickup/sun/sunseed.xml",
	},
	{
		id = "sunstone",
		name = "$item_seed_c",
        desc = "$itemdesc_seed_c",
		image = "data/ui_gfx/items/sunseed_2.png",
		path = "data/entities/items/pickup/sun/sunstone.xml",
	},
	{
		id = "wandstone",
		name = "$item_wandstone",
        desc = "$itemdesc_wandstone",
		image = "data/ui_gfx/items/wandstone.png",
		path = "data/entities/items/pickup/wandstone.xml",
	},
	{
		id = "bloodmoney_10",
		name = "$item_bloodmoney_10",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bloodnugget_6px.png",
		path = "data/entities/items/pickup/bloodmoney_10.xml",
	},
	{
		id = "bloodmoney_50",
		name = "$item_bloodmoney_50",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bloodnugget_9px.png",
		path = "data/entities/items/pickup/bloodmoney_50.xml",
	},
	{
		id = "bloodmoney_200",
		name = "$item_bloodmoney_200",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bloodnugget_12px.png",
		path = "data/entities/items/pickup/bloodmoney_200.xml",
	},
	{
		id = "bloodmoney_1000",
		name = "$item_bloodmoney_1000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bloodnugget_20px.png",
		path = "data/entities/items/pickup/bloodmoney_1000.xml",
	},
	{
		id = "bloodmoney_10000",
		name = "$item_bloodmoney_10000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/blood_idol.png",
		path = "data/entities/items/pickup/bloodmoney_10000.xml",
	},
	{
		id = "bloodmoney_200000",
		name = "$item_bloodmoney_200000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/blood_idol.png",
		path = "data/entities/items/pickup/bloodmoney_200000.xml",
	},
	{
		id = "goldnugget_10",
		name = "$item_goldnugget_10",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/goldnugget_6px.png",
		path = "data/entities/items/pickup/goldnugget_10.xml",
	},
	{
		id = "goldnugget_50",
		name = "$item_goldnugget_50",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/goldnugget_9px.png",
		path = "data/entities/items/pickup/goldnugget_50.xml",
	},
	{
		id = "goldnugget_200",
		name = "$item_goldnugget_200",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/goldnugget_12px.png",
		path = "data/entities/items/pickup/goldnugget_200.xml",
	},
	{
		id = "goldnugget_1000",
		name = "$item_goldnugget_1000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/goldnugget_20px.png",
		path = "data/entities/items/pickup/goldnugget_1000.xml",
	},
	{
		id = "goldnugget_10000",
		name = "$item_goldnugget_10000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/golden_idol.png",
		path = "data/entities/items/pickup/goldnugget_10000.xml",
	},
	{
		id = "goldnugget_200000",
		name = "$item_goldnugget_200000",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/golden_idol.png",
		path = "data/entities/items/pickup/goldnugget_200000.xml",
	},
	{
		id = "summon_portal_broken",
		name = "$action_broken_spell",
        desc = "$actiondesc_broken_spell",
		image = "data/items_gfx/broken_spell.png",
		path = "data/entities/items/pickup/summon_portal_broken.xml",
	},
	{
		id = "broken_wand",
		name = "$item_broken_wand",
        desc = "$item_description_broken_wand",
		image = "data/ui_gfx/items/broken_wand.png",
		path = "data/entities/items/pickup/broken_wand.xml",
	},
	{
		id = "cape",
		name = "$conjurer_reborn_cape_upgrade",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/default.png",
		path = "data/entities/items/pickup/cape.xml",
	},
	{
		id = "chest_leggy",
		name = "$item_chest_treasure",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_random.png",
		path = "data/entities/items/pickup/chest_leggy.xml",
	},
	{
		id = "chest_random",
		name = "$item_chest_treasure",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_random.png",
		path = "data/entities/items/pickup/chest_random.xml",
	},
	{
		id = "chest_random_super",
		name = "$item_chest_treasure",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_random_super.png",
		path = "data/entities/items/pickup/chest_random_super.xml",
	},
	{
		id = "chest_steel",
		name = "$item_chest_treasure",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_steel.png",
		path = "data/entities/buildings/chest_steel.xml",
	},
	{
		id = "chest_dark",
		name = "$item_chest_dark",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_dark.png",
		path = "data/entities/buildings/chest_dark.xml",
	},
	{
		id = "chest_light",
		name = "$item_chest_light",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chest_light.png",
		path = "data/entities/buildings/chest_light.xml",
	},
	{
		id = "utility_box",
		name = "$item_utility_box",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/utility_box.png",
		path = "data/entities/items/pickup/utility_box.xml",
	},
	{
		id = "key",
		name = "$item_key",
        desc = "$itemdesc_key_0",
		image = "data/ui_gfx/items/key.png",
		path = "data/entities/animals/boss_alchemist/key.xml",
	},
	{
		id = "egg_fire",
		name = "$item_egg_fire",
        desc = "$item_description_egg_fire",
		image = "data/ui_gfx/items/egg_red.png",
		path = "data/entities/items/pickup/egg_fire.xml",
	},
	{
		id = "egg_hollow",
		name = "$item_egg_hollow",
        desc = "$itemdesc_egg_hollow",
		image = "data/ui_gfx/items/egg_slime.png",
		path = "data/entities/items/pickup/egg_hollow.xml",
	},
	{
		id = "egg_monster",
		name = "$item_egg",
        desc = "$item_description_egg",
		image = "data/ui_gfx/items/egg.png",
		path = "data/entities/items/pickup/egg_monster.xml",
	},
	{
		id = "egg_red",
		name = "$item_egg",
        desc = "$item_description_egg",
		image = "data/ui_gfx/items/egg_red.png",
		path = "data/entities/items/pickup/egg_red.xml",
	},
	{
		id = "egg_slime",
		name = "$item_egg_slime",
        desc = "$item_description_egg_slime",
		image = "data/ui_gfx/items/egg_slime.png",
		path = "data/entities/items/pickup/egg_slime.xml",
	},
	{
		id = "egg_purple",
		name = "$item_egg_purple",
        desc = "$item_description_egg_purple",
		image = "data/ui_gfx/items/egg_purple.png",
		path = "data/entities/items/pickup/egg_purple.xml",
	},
	{
		id = "egg_spiders",
		name = "$item_egg_purple",
        desc = "$item_description_egg_purple",
		image = "data/ui_gfx/items/egg_purple.png",
		path = "data/entities/items/pickup/egg_spiders.xml",
	},
	{
		id = "egg_worm",
		name = "$item_egg_worm",
        desc = "$item_description_egg_worm",
		image = "data/ui_gfx/items/egg_worm.png",
		path = "data/entities/items/pickup/egg_worm.xml",
	},
	{
		id = "essence_eater",
		name = "$item_essence_stone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_eater.png",
		path = "data/entities/buildings/essence_eater.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_air.png",
        name = "$item_essence_air",
		desc = "$itemdesc_essence_air",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "essence_air",
		path = "data/entities/items/pickup/essence_air.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_alcohol.png",
        name = "$item_essence_alcohol",
		desc = "$itemdesc_essence_alcohol",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "essence_alcohol",
		path = "data/entities/items/pickup/essence_alcohol.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_fire.png",
        name = "$item_essence_fire",
		desc = "$itemdesc_essence_fire",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "essence_fire",
		path = "data/entities/items/pickup/essence_fire.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_laser.png",
        name = "$item_essence_laser",
		desc = "$itemdesc_essence_laser",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "essence_laser",
		path = "data/entities/items/pickup/essence_laser.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/essence_water.png",
        name = "$item_essence_water",
		desc = "$itemdesc_essence_water",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "essence_water",
		path = "data/entities/items/pickup/essence_water.xml",
	},
	{
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/greed_curse.png",
		name = "$item_essence_greed",
		desc = "$logdesc_greed_curse",
		desc2 = "$conjurer_reborn_pickup_danger_tip",
		id = "greed_curse",
		path = "data/entities/items/pickup/greed_curse.xml",
	},
	{
		id = "gourd",
		name = "$item_gourd",
        desc = "$itemdesc_gourd",
		image = "data/ui_gfx/items/gourd.png",
		path = "data/entities/items/pickup/gourd.xml",
	},
	{
		id = "spell_refresh",
		name = "$item_spell_refresh",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/spell_refresh.png",
		path = "data/entities/items/pickup/spell_refresh.xml",
	},
	{
		id = "heart",
		name = "$item_heart",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/heart_extrahp.png",
		path = "data/entities/items/pickup/heart.xml",
	},
	{
		id = "heart_better",
		name = "$item_heart_better",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/heart_extrahp.png",
		path = "data/entities/items/pickup/heart_better.xml",
	},
	{
		id = "heart_evil",
		name = "$item_heart",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/heart_extrahp_evil.png",
		path = "data/entities/items/pickup/heart_evil.xml",
	},
	{
		id = "heart_fullhp",
		name = "$item_heart_fullhp",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/heart.png",
		path = "data/entities/items/pickup/heart_fullhp.xml",
	},
	{
		id = "heart_fullhp_temple",
		name = "$item_heart_fullhp",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/heart.png",
		path = "data/entities/items/pickup/heart_fullhp_temple.xml",
	},
	{
		id = "perk_reroll",
		name = "$item_perk_reroll",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/perk_reroll.png",
		path = "data/entities/items/pickup/perk_reroll.xml",
	},
	{
		id = "jar",
		name = "$item_jar_with_material",
        desc = "$item_description_jar",
		image = "data/ui_gfx/items/jar.png",
		path = "data/entities/items/pickup/jar.xml",
	},
	{
		id = "jar_of_urine",
		name = "$item_jar_with_material",
        desc = "$item_description_jar",
		image = "data/ui_gfx/items/jar.png",
		path = "data/entities/items/pickup/jar_of_urine.xml",
	},
	{
		id = "powder_stash",
		name = "$item_powder_stash_with_material_3",
        desc = "$itemdesc_powder_stash_3",
		image = "data/ui_gfx/items/material_pouch.png",
		path = "data/entities/items/pickup/powder_stash.xml",
	},
	{
		id = "potion",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion.xml",
	},
	{
		id = "potion_empty",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_empty.xml",
	},
	{
		id = "potion_porridge",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_porridge.xml",
	},
	{
		id = "potion_slime",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_slime.xml",
	},
	{
		id = "potion_aggressive",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion_alchemist.png",
		path = "data/entities/items/pickup/potion_aggressive.xml",
	},
	{
		id = "potion_alcohol",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_alcohol.xml",
	},
	{
		id = "potion_random_material",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_random_material.xml",
	},
	{
		id = "potion_secret",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_secret.xml",
	},
	{
		id = "potion_starting",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_starting.xml",
	},
	{
		id = "potion_water",
		name = "$item_potion_with_material",
        desc = "$item_description_potion",
		image = "data/ui_gfx/items/potion.png",
		path = "data/entities/items/pickup/potion_water.xml",
	},
	{
		id = "runestone_metal",
		name = "$item_runestone_metal",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_metal.png",
		path = "data/entities/items/pickup/runestones/runestone_metal.xml",
	},
	{
		id = "runestone_disc",
		name = "$item_runestone_disc",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_disc.png",
		path = "data/entities/items/pickup/runestones/runestone_disc.xml",
	},
	{
		id = "runestone_fireball",
		name = "$item_runestone_fireball",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_fireball.png",
		path = "data/entities/items/pickup/runestones/runestone_fireball.xml",
	},
	{
		id = "runestone_laser",
		name = "$item_runestone_laser",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_laser.png",
		path = "data/entities/items/pickup/runestones/runestone_laser.xml",
	},
	{
		id = "runestone_lava",
		name = "$item_runestone_lava",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_lava.png",
		path = "data/entities/items/pickup/runestones/runestone_lava.xml",
	},
	{
		id = "runestone_null",
		name = "$item_runestone_null",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_null.png",
		path = "data/entities/items/pickup/runestones/runestone_null.xml",
	},
	{
		id = "runestone_slow",
		name = "$item_runestone_slow",
        desc = "$itemdesc_runestone",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/runestone_slow.png",
		path = "data/entities/items/pickup/runestones/runestone_slow.xml",
	},
	{
		id = "sampo",
		name = "$item_mcguffin_12",
        desc = "$itemdesc_mcguffin",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/sampo.png",
		path = "data/entities/animals/boss_centipede/sampo.xml",
	},
	{
		id = "moon",
		name = "$item_moon",
        desc = "$item_description_moon",
		image = "data/ui_gfx/items/moon.png",
		path = "data/entities/items/pickup/moon.xml",
	},
	{
		id = "safe_haven",
		name = "$item_safe_haven",
        desc = "$item_description_safe_haven",
		image = "data/ui_gfx/items/safe_haven.png",
		path = "data/entities/items/pickup/safe_haven.xml",
	},
	{
		id = "druidsoccer_ball",
		name = "Druidsoccer ball",
		desc = "$conjurer_reborn_what_this",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/druidsoccer_ball.png",
		path = "data/entities/items/easter/druidsoccer_ball.xml",
	},
	{
		id = "flute",
		name = "$item_ocarina",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/flute.png",
		path = "data/entities/items/flute.xml",
	},
	{
		id = "kantele",
		name = "$item_kantele",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/kantele.png",
		path = "data/entities/items/kantele.xml",
	},
	{
		id = "starting_bomb_wand",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bomb_wand.png",
		path = "data/entities/items/starting_bomb_wand.xml",
	},
	{
		id = "starting_bomb_wand_rng",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bomb_wand.png",
		path = "data/entities/items/starting_bomb_wand_rng.xml",
	},
	{
		id = "starting_bomb_wand_rng_daily",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/bomb_wand.png",
		path = "data/entities/items/starting_bomb_wand_rng_daily.xml",
	},
	{
		id = "starting_wand",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/handgun.png",
		path = "data/entities/items/starting_wand.xml",
	},
	{
		id = "starting_wand_rng",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/handgun.png",
		path = "data/entities/items/starting_wand_rng.xml",
	},
	{
		id = "starting_wand_rng_daily",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/handgun.png",
		path = "data/entities/items/starting_wand_rng_daily.xml",
	},
	{
		id = "wand_daily_01",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_01.xml",
	},
	{
		id = "wand_daily_02",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_02.xml",
	},
	{
		id = "wand_daily_03",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_03.xml",
	},
	{
		id = "wand_daily_04",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_04.xml",
	},
	{
		id = "wand_daily_05",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_05.xml",
	},
	{
		id = "wand_daily_06",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_daily_06.xml",
	},
	{
		id = "wand_level_01",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_01.xml",
	},
	{
		id = "wand_level_01_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_01_better.xml",
	},
	{
		id = "wand_level_01_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_01_p.xml",
	},
	{
		id = "wand_level_02",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_02.xml",
	},
	{
		id = "wand_level_02_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_02_better.xml",
	},
	{
		id = "wand_level_02_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_02_p.xml",
	},
	{
		id = "wand_level_03",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_03.xml",
	},
	{
		id = "wand_level_03_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_03_better.xml",
	},
	{
		id = "wand_level_03_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_03_p.xml",
	},
	{
		id = "wand_level_04",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_04.xml",
	},
	{
		id = "wand_level_04_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_04_better.xml",
	},
	{
		id = "wand_level_04_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_04_p.xml",
	},
	{
		id = "wand_level_05",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_05.xml",
	},
	{
		id = "wand_level_05_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_05_better.xml",
	},
	{
		id = "wand_level_05_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_05_p.xml",
	},
	{
		id = "wand_level_06",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_06.xml",
	},
	{
		id = "wand_level_06_better",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_06_better.xml",
	},
	{
		id = "wand_level_06_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_06_p.xml",
	},
	{
		id = "wand_level_10",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_level_10.xml",
	},
	{
		id = "wand_petri",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0898.png",
		path = "data/entities/items/wand_petri.xml",
	},
	{
		id = "wand_unshuffle_01",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_01.xml",
	},
	{
		id = "wand_unshuffle_01_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_01_p.xml",
	},
	{
		id = "wand_unshuffle_02",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_02.xml",
	},
	{
		id = "wand_unshuffle_02_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_02_p.xml",
	},
	{
		id = "wand_unshuffle_03",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_03.xml",
	},
	{
		id = "wand_unshuffle_03_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_03_p.xml",
	},
	{
		id = "wand_unshuffle_04",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_04.xml",
	},
	{
		id = "wand_unshuffle_04_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_04_p.xml",
	},
	{
		id = "wand_unshuffle_05",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_05.xml",
	},
	{
		id = "wand_unshuffle_05_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_05_p.xml",
	},
	{
		id = "wand_unshuffle_06",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_06.xml",
	},
	{
		id = "wand_unshuffle_06_p",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_06_p.xml",
	},
	{
		id = "wand_unshuffle_10",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/machinegun.png",
		path = "data/entities/items/wand_unshuffle_10.xml",
	},
	{
		id = "base_wand_level_1",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0484.png",
		path = "data/entities/items/wands/level_01/base_wand_level_1.xml",
	},
	{
		id = "wand_001",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0484.png",
		path = "data/entities/items/wands/level_01/wand_001.xml",
	},
	{
		id = "wand_002",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0654.png",
		path = "data/entities/items/wands/level_01/wand_002.xml",
	},
	{
		id = "wand_003",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0958.png",
		path = "data/entities/items/wands/level_01/wand_003.xml",
	},
	{
		id = "wand_004",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0516.png",
		path = "data/entities/items/wands/level_01/wand_004.xml",
	},
	{
		id = "wand_005",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0484.png",
		path = "data/entities/items/wands/level_01/wand_005.xml",
	},
	{
		id = "wand_006",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0058.png",
		path = "data/entities/items/wands/level_01/wand_006.xml",
	},
	{
		id = "wand_007",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0120.png",
		path = "data/entities/items/wands/level_01/wand_007.xml",
	},
	{
		id = "wand_008",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0898.png",
		path = "data/entities/items/wands/level_01/wand_008.xml",
	},
	{
		id = "wand_009",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0724.png",
		path = "data/entities/items/wands/level_01/wand_009.xml",
	},
	{
		id = "wand_010",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0326.png",
		path = "data/entities/items/wands/level_01/wand_010.xml",
	},
	{
		id = "wand_011",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0374.png",
		path = "data/entities/items/wands/level_01/wand_011.xml",
	},
	{
		id = "wand_012",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0324.png",
		path = "data/entities/items/wands/level_01/wand_012.xml",
	},
	{
		id = "wand_013",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0309.png",
		path = "data/entities/items/wands/level_01/wand_013.xml",
	},
	{
		id = "wand_014",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0230.png",
		path = "data/entities/items/wands/level_01/wand_014.xml",
	},
	{
		id = "wand_015",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0063.png",
		path = "data/entities/items/wands/level_01/wand_015.xml",
	},
	{
		id = "wand_016",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_0830.png",
		path = "data/entities/items/wands/level_01/wand_016.xml",
	},
	{
		id = "wand_017",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wand_1000.png",
		path = "data/entities/items/wands/level_01/wand_017.xml",
	},
	{
		id = "wand_vasta",
		name = "$item_vasta",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/vasta.png",
		path = "data/entities/items/wand_vasta.xml",
	},
	{
		id = "wand_vihta",
		name = "$item_vihta",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/vihta.png",
		path = "data/entities/items/wand_vihta.xml",
	},
	{
		id = "wand_arpaluu",
		name = "$item_wand_arpaluu",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/skull_01.png",
		path = "data/entities/items/wand_arpaluu.xml",
	},
	{
		id = "wand_kiekurakeppi",
		name = "$item_wand_kiekurakeppi",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/wood_01.png",
		path = "data/entities/items/wand_kiekurakeppi.xml",
	},
	{
		id = "wand_ruusu",
		name = "$item_wand_ruusu",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/plant_01.png",
		path = "data/entities/items/wand_ruusu.xml",
	},
	{
		id = "wand_valtikka",
		name = "$item_wand_valtikka",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/scepter_01.png",
		path = "data/entities/items/wand_valtikka.xml",
	},
	{
		id = "wand_varpuluuta",
		name = "$item_wand_varpuluuta",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/plant_02.png",
		path = "data/entities/items/wand_varpuluuta.xml",
	},
	{
		id = "experimental_wand_1",
		name = "$item_wand_experimental_1",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/experimental_wand_1.png",
		path = "data/entities/items/wands/experimental/experimental_wand_1.xml",
	},
	{
		id = "experimental_wand_2",
		name = "$item_wand_experimental_2",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/experimental_wand_2.png",
		path = "data/entities/items/wands/experimental/experimental_wand_2.xml",
	},
	{
		id = "experimental_wand_3",
		name = "$item_wand_experimental_1",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/actual_wand_honest.png",
		path = "data/entities/items/wands/experimental/experimental_wand_3.xml",
	},
	{
		id = "experimental_wand_4",
		name = "$item_chainsaw",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/chainsaw.png",
		path = "data/entities/items/wands/experimental/experimental_wand_4.xml",
	},
	{
		id = "wand_leukaluu",
		name = "$item_leukaluu",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/leukaluu.png",
		path = "data/entities/items/wand_leukaluu.xml",
	},
	{
		id = "leukaluu_kantele",
		name = "$item_leukaluu_kantele",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/leukaluu_kantele.png",
		path = "data/entities/items/leukaluu_kantele.xml",
	},
	{
		id = "wand_good_1",
		name = "$item_wand_good_1",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/good_01.png",
		path = "data/entities/items/wands/wand_good/wand_good_1.xml",
	},
	{
		id = "wand_good_2",
		name = "$item_wand_good_2",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/good_02.png",
		path = "data/entities/items/wands/wand_good/wand_good_2.xml",
	},
	{
		id = "wand_good_3",
		name = "$item_wand_good_3",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/good_03.png",
		path = "data/entities/items/wands/wand_good/wand_good_3.xml",
	},
	{
		id = "digger_01",
		name = "$item_wand",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/scepter_01.png",
		path = "data/entities/items/wands/custom/digger_01.xml",
    },
	{
		id = "book_corpse",
		name = "$booktitle_corpse",
		desc = "$bookdesc_corpse",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_corpse.xml",
    },
	{
		id = "book_tree",
		name = "$booktitle_tree",
		desc = "$bookdesc_tree",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_tree.xml",
	},
	{
		id = "book_00",
		name = "$booktitle00",
		desc = "$bookdesc00",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_00.xml",
	},
	{
		id = "book_01",
		name = "$booktitle01",
		desc = "$bookdesc01",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_01.xml",
	},
	{
		id = "book_02",
		name = "$booktitle02",
		desc = "$bookdesc02",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_02.xml",
	},
	{
		id = "book_03",
		name = "$booktitle03",
		desc = "$bookdesc03",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_03.xml",
	},
	{
		id = "book_04",
		name = "$booktitle04",
		desc = "$bookdesc04",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_04.xml",
	},
	{
		id = "book_05",
		name = "$booktitle05",
		desc = "$bookdesc05",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_05.xml",
	},
	{
		id = "book_06",
		name = "$booktitle06",
		desc = "$bookdesc06",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_06.xml",
	},
	{
		id = "book_07",
		name = "$booktitle07",
		desc = "$bookdesc07",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_07.xml",
	},
	{
		id = "book_08",
		name = "$booktitle08",
		desc = "$bookdesc08",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_08.xml",
	},
	{
		id = "book_09",
		name = "$booktitle09",
		desc = "$bookdesc09",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_09.xml",
	},
	{
		id = "book_10",
		name = "$booktitle10",
		desc = "$bookdesc10",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/emerald_tablet.png",
		path = "data/entities/items/books/book_10.xml",
    },
	{
		id = "base_forged",
		name = "$booktitle02",
		desc = "$bookdesc02_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
            local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
			WriteItemNameDesc(result, "$booktitle02", "$bookdesc02_forged")
			return result
		end,
	},
	{
		id = "base_forged",
		name = "$booktitle04",
		desc = "$bookdesc04_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle04", "$bookdesc04_forged")
			return result
		end,
    },
	{
		id = "base_forged",
		name = "$booktitle05",
		desc = "$bookdesc05_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle05", "$bookdesc05_forged")
			return result
		end,
    },
	{
		id = "base_forged",
		name = "$booktitle06",
		desc = "$bookdesc06_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle06", "$bookdesc06_forged")
			return result
		end,
    },
	{
		id = "base_forged",
		name = "$booktitle07",
		desc = "$bookdesc07_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle07", "$bookdesc07_forged")
			return result
		end,
	},
	{
		id = "base_forged",
		name = "$booktitle08",
		desc = "$bookdesc08_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle08", "$bookdesc08_forged")
			return result
		end,
    },
	{
		id = "base_forged",
		name = "$booktitle09",
		desc = "$bookdesc09_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle09", "$bookdesc09_forged")
			return result
		end,
    },
	{
		id = "base_forged",
		name = "$booktitle10",
		desc = "$bookdesc10_forged",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		spawn_func = function(x, y)
			local result = EntityLoad("data/entities/items/books/base_forged.xml", x, y)
            WriteItemNameDesc(result, "$booktitle10", "$bookdesc10_forged")
			return result
		end,
    },
	{
		id = "book_all_spells",
		name = "$booktitle_allspells",
		desc = "$bookdesc_allspells",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/laboratory_tablet.png",
		path = "data/entities/items/books/book_all_spells.xml",
    },
	{
		id = "book_barren",
		name = "$booktitle_barren",
		desc = "$bookdesc_barren",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_barren.xml",
    },
	{
		id = "book_bunker",
		name = "$booktitle_fisher",
		desc = "$bookdesc_fisher",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_bunker.xml",
    },
	{
		id = "book_diamond",
		name = "$item_book_diamond",
		desc = "$itemdesc_book_diamond",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_diamond.xml",
    },
	{
		id = "book_essences",
		name = "$item_book_essences",
		desc = "$itemdesc_book_essences",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_essences.xml",
    },
	{
		id = "book_hint",
		name = "$item_book_hint",
		desc = "$itemdesc_book_hint",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_hint.xml",
    },
	{
		id = "book_mestari",
		name = "$booktitle_mestari",
		desc = "$bookdesc_mestari",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_mestari.xml",
    },
	{
		id = "book_moon",
		name = "$item_book_moon",
		desc = "$itemdesc_book_moon",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_moon.xml",
    },
	{
		id = "book_music_a",
		name = "$item_book_music",
		desc = "$itemdesc_book_music",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_music_a.xml",
    },
	{
		id = "book_music_b",
		name = "$item_book_music_b",
		desc = "$itemdesc_book_music_b",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_music_b.xml",
    },
	{
		id = "book_music_c",
		name = "$item_book_music_c",
		desc = "$itemdesc_book_music_c",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_music_c.xml",
    },
	{
		id = "book_robot",
		name = "$item_book_robot",
		desc = "$itemdesc_book_robot",
		image = "data/items_gfx/book.png",
		path = "data/entities/items/books/book_robot.xml",
    },
	{
		id = "book_s_a",
		name = "$item_book_s_a",
		desc = "$itemdesc_book_s_a",
		image = "data/items_gfx/book_s.png",
		path = "data/entities/items/books/book_s_a.xml",
    },
	{
		id = "book_s_b",
		name = "$item_book_s_a",
		desc = "$itemdesc_book_s_b",
		image = "data/items_gfx/book_s.png",
		path = "data/entities/items/books/book_s_b.xml",
    },
	{
		id = "book_s_c",
		name = "$item_book_s_a",
		desc = "$itemdesc_book_s_c",
		image = "data/items_gfx/book_s.png",
		path = "data/entities/items/books/book_s_c.xml",
    },
	{
		id = "book_s_d",
		name = "$item_book_s_a",
		desc = "$itemdesc_book_s_d",
		image = "data/items_gfx/book_s.png",
		path = "data/entities/items/books/book_s_d.xml",
    },
	{
		id = "book_s_e",
		name = "$item_book_s_a",
		desc = "$itemdesc_book_s_e",
		image = "data/items_gfx/book_s.png",
		path = "data/entities/items/books/book_s_e.xml",
    },
	{
		id = "orb_00",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_00.xml",
	},
	{
		id = "orb_01",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_01.xml",
	},
	{
		id = "orb_02",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_02.xml",
	},
	{
		id = "orb_03",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_03.xml",
	},
	{
		id = "orb_04",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_04.xml",
	},
	{
		id = "orb_05",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_05.xml",
	},
	{
		id = "orb_06",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_06.xml",
	},
	{
		id = "orb_07",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_07.xml",
	},
	{
		id = "orb_08",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_08.xml",
	},
	{
		id = "orb_09",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_09.xml",
	},
	{
		id = "orb_10",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_10.xml",
	},
	{
		id = "orb_11",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_11.xml",
	},
	{
		id = "orb_13",
		name = "$item_orb",
		image = "mods/conjurer_reborn/files/gfx/pickup_icons/true_knowledge_orb.png",
		path = "data/entities/items/orbs/orb_13.xml",
	},
}
